<a href="https://colab.research.google.com/github/venkat123reddy/DeepLearning/blob/main/Assignment3_task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import math

def softmax(x):
    """Compute softmax row-wise."""
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)

def scaled_dot_product_attention(Q, K, V):
    # Step 1: Dot product of Q and Kᵀ
    scores = np.dot(Q, K.T)
    print("Dot product QKᵀ:\n", scores)

    # Step 2: Scale by √d (d is key dimension)
    d_k = K.shape[-1]
    scaled_scores = scores / math.sqrt(d_k)
    print("\nScaled Scores:\n", scaled_scores)

    # Step 3: Softmax to get attention weights
    attention_weights = softmax(scaled_scores)
    print("\nAttention Weights (Softmax):\n", attention_weights)

    # Step 4: Multiply attention weights by V
    output = np.dot(attention_weights, V)
    print("\nFinal Output (Attention Output):\n", output)

    return attention_weights, output

# Test inputs
Q = np.array([[1, 0, 1, 0],
              [0, 1, 0, 1]])
K = np.array([[1, 0, 1, 0],
              [0, 1, 0, 1]])
V = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

# Run scaled dot-product attention
attention_weights, output = scaled_dot_product_attention(Q, K, V)


Dot product QKᵀ:
 [[2 0]
 [0 2]]

Scaled Scores:
 [[1. 0.]
 [0. 1.]]

Attention Weights (Softmax):
 [[0.73105858 0.26894142]
 [0.26894142 0.73105858]]

Final Output (Attention Output):
 [[2.07576569 3.07576569 4.07576569 5.07576569]
 [3.92423431 4.92423431 5.92423431 6.92423431]]
