<a href="https://colab.research.google.com/github/venkat123reddy/DeepLearning/blob/main/Assignment_1_Q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
# Step 1: Create a random tensor of shape (4, 6)
tensor = tf.random.uniform(shape=(4, 6))
print("Original Tensor:\n", tensor)

Original Tensor:
 tf.Tensor(
[[0.6715152  0.81201863 0.6304853  0.33876002 0.26223028 0.4755398 ]
 [0.03197324 0.69418776 0.94581604 0.44487786 0.01668    0.5371027 ]
 [0.20518327 0.9058622  0.81287324 0.6412629  0.01367557 0.91888547]
 [0.08205307 0.10606432 0.4122926  0.63035    0.0110358  0.08660662]], shape=(4, 6), dtype=float32)


In [4]:
rank_original = tf.rank(tensor).numpy()
shape_original = tf.shape(tensor).numpy()
print(f"Original Rank: {rank_original}")
print(f"Original Shape: {shape_original}")

Original Rank: 2
Original Shape: [4 6]


In [5]:
# Step 3: Reshape it to (2, 3, 4) and transpose it to (3, 2, 4)
reshaped_tensor = tf.reshape(tensor, (2, 3, 4))
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])

In [6]:
# Display the reshaped and transposed tensor
print("Transposed Tensor (shape [3, 2, 4]):\n", transposed_tensor)

Transposed Tensor (shape [3, 2, 4]):
 tf.Tensor(
[[[0.6715152  0.81201863 0.6304853  0.33876002]
  [0.20518327 0.9058622  0.81287324 0.6412629 ]]

 [[0.26223028 0.4755398  0.03197324 0.69418776]
  [0.01367557 0.91888547 0.08205307 0.10606432]]

 [[0.94581604 0.44487786 0.01668    0.5371027 ]
  [0.4122926  0.63035    0.0110358  0.08660662]]], shape=(3, 2, 4), dtype=float32)


In [7]:
# Print new rank and shape after transformation
rank_transposed = tf.rank(transposed_tensor).numpy()
shape_transposed = tf.shape(transposed_tensor).numpy()
print(f" Transposed Rank: {rank_transposed}")
print(f" Transposed Shape: {shape_transposed}")

 Transposed Rank: 3
 Transposed Shape: [3 2 4]


In [8]:
# Step 4: Create a smaller tensor of shape (1, 4) and broadcast it
smaller_tensor = tf.random.uniform(shape=(1, 4))

In [9]:
# Broadcasted addition - TensorFlow automatically broadcasts the smaller tensor
broadcasted_result = transposed_tensor + smaller_tensor
print("Result after broadcasting and adding:\n", broadcasted_result)

Result after broadcasting and adding:
 tf.Tensor(
[[[0.8653048  1.4675436  1.2524858  0.47404075]
  [0.39897287 1.5613872  1.4348737  0.7765436 ]]

 [[0.45601988 1.1310648  0.6539737  0.8294685 ]
  [0.20746517 1.5744104  0.7040535  0.24134505]]

 [[1.1396056  1.1004028  0.63868046 0.6723834 ]
  [0.6060822  1.285875   0.63303626 0.22188735]]], shape=(3, 2, 4), dtype=float32)


In [10]:
# Step 5: Explanation of broadcasting in TensorFlow
explanation = """
📘 TensorFlow Broadcasting:
Broadcasting allows tensors of different shapes to be combined during arithmetic operations.
In this case, a tensor of shape (1, 4) is broadcast across a (3, 2, 4) tensor,
aligning on the last dimension (4) and expanding dimensions (1 → 3 and 2).
"""
print(explanation)


📘 TensorFlow Broadcasting:
Broadcasting allows tensors of different shapes to be combined during arithmetic operations.
In this case, a tensor of shape (1, 4) is broadcast across a (3, 2, 4) tensor,
aligning on the last dimension (4) and expanding dimensions (1 → 3 and 2).

