<a href="https://colab.research.google.com/github/venkat123reddy/DeepLearning/blob/main/Assignment_2_task_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf
import numpy as np

# Create a 4x4 random input matrix
input_matrix = np.random.randint(0, 10, (1, 4, 4, 1)).astype(np.float32)

# Max Pooling (2x2)
max_pool = tf.nn.max_pool2d(input_matrix, ksize=2, strides=2, padding='VALID')

# Average Pooling (2x2)
avg_pool = tf.nn.avg_pool2d(input_matrix, ksize=2, strides=2, padding='VALID')

# Display results
print("Original 4x4 matrix:\n", input_matrix[0, :, :, 0])  # ✅ remove .numpy()
print("\nMax Pooled (2x2):\n", max_pool[0, :, :, 0].numpy())  # ✅ this is a Tensor
print("\nAverage Pooled (2x2):\n", avg_pool[0, :, :, 0].numpy())  # ✅ this is a Tensor


Original 4x4 matrix:
 [[9. 0. 0. 7.]
 [1. 7. 8. 1.]
 [2. 9. 9. 6.]
 [8. 9. 6. 8.]]

Max Pooled (2x2):
 [[9. 8.]
 [9. 9.]]

Average Pooled (2x2):
 [[4.25 4.  ]
 [7.   7.25]]
