<a href="https://colab.research.google.com/github/venkat123reddy/DeepLearning/blob/main/assignment2_q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import tensorflow as tf



In [2]:
# Define the input matrix (5x5)
input_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32)



In [3]:
# Reshape input to 4D tensor: [batch, height, width, channels]
input_tensor = input_matrix.reshape(1, 5, 5, 1)


In [4]:

# Define the kernel (3x3)
kernel = np.array([
    [0, 1, 0],
    [1, -4, 1],
    [0, 1, 0]
], dtype=np.float32)


In [5]:
# Reshape kernel to 4D tensor: [height, width, in_channels, out_channels]
kernel_tensor = kernel.reshape(3, 3, 1, 1)



In [7]:
# Function to perform convolution and print output
def perform_convolution(stride, padding):
    result = tf.nn.conv2d(input_tensor, kernel_tensor, strides=[1, stride, stride, 1], padding=padding)
    print(f"\nStride = {stride}, Padding = '{padding}'")
    print(result.numpy().squeeze())  # Remove extra dimensions for display



In [8]:
# Perform required convolutions
perform_convolution(stride=1, padding='VALID')
perform_convolution(stride=1, padding='SAME')
perform_convolution(stride=2, padding='VALID')
perform_convolution(stride=2, padding='SAME')


Stride = 1, Padding = 'VALID'
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Stride = 1, Padding = 'SAME'
[[  4.   3.   2.   1.  -6.]
 [ -5.   0.   0.   0. -11.]
 [-10.   0.   0.   0. -16.]
 [-15.   0.   0.   0. -21.]
 [-46. -27. -28. -29. -56.]]

Stride = 2, Padding = 'VALID'
[[0. 0.]
 [0. 0.]]

Stride = 2, Padding = 'SAME'
[[  4.   2.  -6.]
 [-10.   0. -16.]
 [-46. -28. -56.]]
